In [1]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sreen\anaconda3\lib\site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in c:\users\sreen\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [3]:
from openpyxl import load_workbook

In [12]:
workbook = load_workbook(filename="reviews-samples.xlsx")

In [14]:
workbook.sheetnames

['amazon_reviews_us_sheet1', 'amazon_reviews_us_sheet2']

In [16]:
sheet1 = workbook.active

In [20]:
sheet1.title

'amazon_reviews_us_sheet1'

In [24]:
sheet1["B2"].value

3653882

In [28]:
sheet1.cell(row=10,column=4).value

"G-Shock Men's Grey Sport Watch"

In [30]:
sheet1["D10"].value

"G-Shock Men's Grey Sport Watch"

In [34]:
sheet1["A1:C2"]

((<Cell 'amazon_reviews_us_sheet1'.A1>,
  <Cell 'amazon_reviews_us_sheet1'.B1>,
  <Cell 'amazon_reviews_us_sheet1'.C1>),
 (<Cell 'amazon_reviews_us_sheet1'.A2>,
  <Cell 'amazon_reviews_us_sheet1'.B2>,
  <Cell 'amazon_reviews_us_sheet1'.C2>))

In [40]:
for value in sheet1.iter_rows(min_row=1,max_row=10,min_col=4,max_col=5,values_only=True):
    print(value)

('product_title', 'product_category')
('Invicta Women\'s 15150 "Angel" 18k Yellow Gold Ion-Plated Stainless Steel and Brown Leather Watch', 'Watches')
("Kenneth Cole New York Women's KC4944 Automatic Silver Automatic Mesh Bracelet Analog Watch", 'Watches')
('Ritche 22mm Black Stainless Steel Bracelet Watch Band Strap Pebble Time/Pebble Classic', 'Watches')
("Citizen Men's BM8180-03E Eco-Drive Stainless Steel Watch with Green Canvas Band", 'Watches')
("Orient ER27009B Men's Symphony Automatic Stainless Steel Black Dial Mechanical Watch", 'Watches')
("Casio Men's GW-9400BJ-1JF G-Shock Master of G Rangeman Digital Solar Black Carbon Fiber Insert Watch", 'Watches')
("Fossil Women's ES3851 Urban Traveler Multifunction Stainless Steel Watch - Rose", 'Watches')
('INFANTRY Mens Night Vision Analog Quartz Wrist Watch with Nato Nylon Watchband-Red.', 'Watches')
("G-Shock Men's Grey Sport Watch", 'Watches')

In [48]:
import json
workbook = load_workbook(filename="reviews-samples.xlsx")
sheet1 = workbook.active
products={}
for row in sheet1.iter_rows(min_row=2,min_col=4,max_col=7,values_only=True):
    product_id=row[0]
    product = { 
        "parent":row[1],
        "title":row[2],
        "category":row[3]
    }
    products[product_id]=product
    
print(json.dumps(products))

{"B00FALQ1ZC": {"parent": 937001370, "title": "Invicta Women's 15150 \"Angel\" 18k Yellow Gold Ion-Plated Stainless Steel and Brown Leather Watch", "category": "Watches"}, "B00D3RGO20": {"parent": 484010722, "title": "Kenneth Cole New York Women's KC4944 Automatic Silver Automatic Mesh Bracelet Analog Watch", "category": "Watches"}, "B00DKYC7TK": {"parent": 361166390, "title": "Ritche 22mm Black Stainless Steel Bracelet Watch Band Strap Pebble Time/Pebble Classic", "category": "Watches"}, "B000EQS1JW": {"parent": 958035625, "title": "Citizen Men's BM8180-03E Eco-Drive Stainless Steel Watch with Green Canvas Band", "category": "Watches"}, "B00A6GFD7S": {"parent": 765328221, "title": "Orient ER27009B Men's Symphony Automatic Stainless Steel Black Dial Mechanical Watch", "category": "Watches"}, "B00EYSOSE8": {"parent": 230493695, "title": "Casio Men's GW-9400BJ-1JF G-Shock Master of G Rangeman Digital Solar Black Carbon Fiber Insert Watch", "category": "Watches"}, "B00WM0QA3M": {"parent": 549298279, "title": "Fossil Women's ES3851 Urban Traveler Multifunction Stainless Steel Watch - Rose", "category": "Watches"}, "B00A4EYBR0": {"parent": 844009113, "title": "INFANTRY Mens Night Vision Analog Quartz Wrist Watch with Nato Nylon Watchband-Red.", "category": "Watches"}, "B00MAMPGGE": {"parent": 263720892, "title": "G-Shock Men's Grey Sport Watch", "category": "Watches"}, "B004LBPB7Q": {"parent": 124278407, "title": "Heiden Quad Watch Winder in Black Leather", "category": "Watches"}, "B00KGTVGKS": {"parent": 28017857, "title": "Fossil Women's ES3621 Serena Crystal-Accented Two-Tone Stainless Steel Watch", "category": "Watches"}, "B0039UT5OU": {"parent": 685450910, "title": "Casio General Men's Watches Sporty Digital AE-2000W-1AVDF - WW", "category": "Watches"}, "B00MPF0XJQ": {"parent": 767769082, "title": "2Tone Gold Silver Cable Band Ladies Bangle Cuff Watch", "category": "Watches"}, "B003P1OHHS": {"parent": 648595227, "title": "Bulova Men's 98B143 Precisionist Charcoal Grey Dial Bracelet Watch", "category": "Watches"}, "B00R70YEOE": {"parent": 457338020, "title": "Casio - G-Shock - Gulfmaster - Black - GWN1000C-1A", "category": "Watches"}, "B000FVE3BG": {"parent": 824370661, "title": "Invicta Men's 3329 Force Collection Lefty Watch", "category": "Watches"}, "B008X6JB12": {"parent": 814431355, "title": "Seiko Women's SUT068 Dress Solar Classic Diamond-Accented Two-Tone Stainless Steel Watch", "category": "Watches"}, "B0040UOFPW": {"parent": 187700878, "title": "Anne Klein Women's 109271MPTT Swarovski Crystal Accented Two-Tone Multi-Chain Bracelet Watch", "category": "Watches"}, "B00UR2R5UY": {"parent": 594315262, "title": "Guess U13630G1 Men's day and date Gunmetal dial Gunmetal tone bracelet", "category": "Watches"}, "B00HFF57L0": {"parent": 520810507, "title": "Nixon Men's Geo Volt Sentry Stainless Steel Watch with Link Bracelet", "category": "Watches"}, "B00F5O06E6": {"parent": 601596859, "title": "Nautica Men's N14699G BFD 101 Chrono Classic Stainless Steel Watch with Brown Band", "category": "Watches"}, "B00CHS398I": {"parent": 798261110, "title": "HDE Watch Link Pin Remover Band Strap Repair Tool Kit for Watchmakers with Pack of 3 Extra Pins", "category": "Watches"}, "B003OQ4TA4": {"parent": 557813802, "title": "Timex Women's Q7B860 Padded Calfskin 8mm Black Replacement Watchband", "category": "Watches"}, "B007X0SYEY": {"parent": 22870009, "title": "Movado Men's 0606545 \"Museum\" Perforated Black-Rubber Strap Sport Watch", "category": "Watches"}, "B005KPL7FM": {"parent": 269520616, "title": "Invicta Men's 6674 Corduba Chronograph Black Dial Polyurethane Watch", "category": "Watches"}, "B00FNIFI2O": {"parent": 330558574, "title": "Szanto Men's SZ 2001 2000 Series Classic Vintage-Inspired Stainless Steel Watch with Pebbled Leather Band", "category": "Watches"}, "B005JVP0FU": {"parent": 220345054, "title": "Casio Men's MRW200H-7EV Sport Resin Watch", "category": "Watches"}, "B004M23SDI": {"parent": 299884359, "title": "Casio F-108WH-2AEF Mens Blue Digital Watch", "category": "Watches"}, "B00RV2L8CE": {"parent": 714311106, "title": "August Steiner Men's AS8160TTG Silver And Gold Swiss Quartz Watch with Black Dial and Two Tone Bracelet", "category": "Watches"}, "B000JQJS6M": {"parent": 926299553, "title": "Invicta Men's 8928OB Pro Diver Gold Stainless Steel Two-Tone Automatic Watch", "category": "Watches"}, "B00VXLJD44": {"parent": 578998634, "title": "BOS Men's Automatic self-wind mechanical Pointer Skeleton Watch Black Dial Stainless Steel Band 9008", "category": "Watches"}, "B004EFGBW8": {"parent": 727624097, "title": "Luminox Men's 3081 Evo Navy SEAL Chronograph Watch", "category": "Watches"}, "B00G9X76DG": {"parent": 86861596, "title": "INFANTRY Mens 50mm Big Face Military Tactical Analog Digital Sport Wrist Watch Black Silicone Band", "category": "Watches"}, "B00SFTTZ9U": {"parent": 8403354, "title": "BUREI Dress Women's Minimalist Wrist Watches with Date Analog Quartz Stainless Steel and Ultra Slim Dial", "category": "Watches"}, "B00NC8PMUK": {"parent": 944169262, "title": "Motorola Moto 360 Modern Timepiece Smart Watch - Black Leather 00418NARTL", "category": "Watches"}, "B00C1C5J9W": {"parent": 851584415, "title": "Domire Fashion Accessories Trial Order New Quartz Fashion Weave Wrap Around Leather Bracelet Lady Woman Butterfly Wrist Watch", "category": "Watches"}, "B000GB0G5M": {"parent": 492842685, "title": "Casio Women's LQ139B-1B Classic Round Analog Watch", "category": "Watches"}, "B00F8AWMXA": {"parent": 397647155, "title": "Invicta Men's 15256 I-Force Gunmetal Ion-Plated Stainless Steel Watch with Black Leather Strap", "category": "Watches"}, "B005MDPAPU": {"parent": 645499118, "title": "Casio Men's Slim Solar Multi-Function Analog-Digital Watch", "category": "Watches"}, "B006C8NJY8": {"parent": 865472849, "title": "TS6202BLK 8 Belt Box Organizer Black Leather XL Compartments", "category": "Watches"}, "B00791YURC": {"parent": 310034618, "title": "Casio Men's GW2310FB-1CR G-Shock Shock Resistant Multifunction Watch", "category": "Watches"}, "B00S69FO0I": {"parent": 406011595, "title": "U.S. Polo Assn. Sport Men's US9506 Analog-Digital Display Silver-Tone Watch with Textured Band", "category": "Watches"}, "B00C7IQBRY": {"parent": 201258316, "title": "Cerentino Women's CR106-TQ  Turquoise Silicone Rubber Rhinestones Watch", "category": "Watches"}, "B009S4U1TY": {"parent": 830280907, "title": "Batman Kids' BAT4072 Black Rubber Batman Logo Strap Watch", "category": "Watches"}, "B000B55AEA": {"parent": 851729310, "title": "Timex Easy Reader Day-Date Leather Strap Watch", "category": "Watches"}, "B0053HDR78": {"parent": 576694666, "title": "Casio F108WH Water Resistant Digital Blue Resin Strap Watch", "category": "Watches"}, "B008OIOLQO": {"parent": 340110662, "title": "Ingersoll Men's IN1824CR Monticello Fine Automatic Timepiece Cream Dial Watch", "category": "Watches"}, "B009PQB036": {"parent": 696981257, "title": "Lucien Piccard Men's 11576-YG-01 Clariden Black Textured Dial Watch", "category": "Watches"}, "B007X0E178": {"parent": 953514677, "title": "XOXO Women's XO5478 Rhinestone-Accented Two-Tone Watch", "category": "Watches"}, "B00BXQSHRI": {"parent": 714629498, "title": "Watch Case Press with 12 Nylon Dies, Watch Case Closer Set", "category": "Watches"}, "B00ZI3SGXM": {"parent": 294102740, "title": "Stuhrling Original Women's 956.02 Symphony Gold-Tone Watch with Brown Genuine Leather Band", "category": "Watches"}, "B0053A0HB4": {"parent": 199546574, "title": "Casio G-shock Mudman Multiband6 Japanese Model [ Gw-9300-1jf ]", "category": "Watches"}, "B00QBTQX50": {"parent": 29617990, "title": "iStrap Calfskin Leather Watch Band Replacement Choice of Color & Width (18mm,19mm, 20mm,21mm or 22mm)", "category": "Watches"}, "B00G3JSF22": {"parent": 978361500, "title": "G-SHOCK Men's GA-100 Neon Highlights Watch", "category": "Watches"}, "B002NQXYL6": {"parent": 161383158, "title": "Voguestrap TX046801XL Allstrap 16-20mm Brown Extra-Long-Length Fits Fast-Wrap Expedition Watchband", "category": "Watches"}, "B004MAZN3I": {"parent": 165342893, "title": "Seiko Men's SNKK27 Seiko 5 Stainless Steel Automatic Watch", "category": "Watches"}, "B000JQFX1G": {"parent": 400836338, "title": "Invicta Men's 8926OB Pro Diver Stainless Steel Automatic Watch with Link Bracelet", "category": "Watches"}, "B00A6B9N6U": {"parent": 491671113, "title": "Swiss Legend Women's 11044D-01 Neptune Black Dial Watch with Silicone Band", "category": "Watches"}, "B00HJ7T0OY": {"parent": 822340800, "title": "Absolute Hot Iron man Super Hero build-in Blue LED for Men's luxury Army military Wrist Watches", "category": "Watches"}, "B004401KHE": {"parent": 604208769, "title": "Seiko Men's White Dial Brown Leather Easy Reader Solar Calendar Watch", "category": "Watches"}, "B001UGDB0O": {"parent": 762085956, "title": "Michael Kors Womens MK5145 - Runway Chronograph", "category": "Watches"}, "B00L4JRXIS": {"parent": 627047973, "title": "Armitron Sport Women's 25/6416 Easy To Read Dial Resin Strap Watch", "category": "Watches"}, "B009PQB5K4": {"parent": 418141913, "title": "Lucien Piccard Men's 11577-RG-02S Stockhorn Silver Textured Dial Brown Leather Watch", "category": "Watches"}, "B003M2G0SY": {"parent": 908936114, "title": "LEGO Star Wars Yoda Kids Buildable Watch with Link Bracelet and Minifigure | green/gray | plastic | 28mm case diameter| analog quartz | boy girl | official", "category": "Watches"}, "B002SSUQFG": {"parent": 354933056, "title": "Seiko Men's SNK809 Seiko 5 Automatic Stainless Steel Watch with Black Canvas Strap", "category": "Watches"}, "B003622WUK": {"parent": 890272218, "title": "Tissot Women's T0492103303300 PR 100 Gold-Tone Silver Dial Watch", "category": "Watches"}, "B00L8M9Z32": {"parent": 686288185, "title": "CASIO BABY-G (BG-6900SG-8JF) GLITTER DIAL SERIES LADY'S WATCH JAPANESE MODEL 2014 JULY RELEASED", "category": "Watches"}, "B000GAWSA4": {"parent": 700023949, "title": "Casio Men's AW80V-1BV", "category": "Watches"}, "B004YM2FV2": {"parent": 649128875, "title": "Bling Jewelry Plated Classic Round CZ Ladies Watch", "category": "Watches"}, "B008RNKIV8": {"parent": 341504925, "title": "Citizen Men's AT8020-54L Blue Angels Stainless Steel Eco-Drive Dress Watch", "category": "Watches"}, "B000SZNTLO": {"parent": 544270597, "title": "Timex Ironman Sleek 50-Lap Full Size", "category": "Watches"}, "B00MNC53XW": {"parent": 567086073, "title": "Outop Wholesale Lot of 5pcs Womens Girls Butterfly Bracelet Wrist Watches", "category": "Watches"}, "B00BF77S2K": {"parent": 479360900, "title": "Timex Kids' T7B9829J IronKids Translucent Blue Sport Watch", "category": "Watches"}, "B00OHD6SLG": {"parent": 721711830, "title": "Cool Men's Racer Military Pilot Army Silicone Sports Watch", "category": "Watches"}, "B003DIP9BQ": {"parent": 941077778, "title": "XOXO Women's XO110 Silver Dial Gold-tone Bracelet Watch", "category": "Watches"}, "B00L3VGTA0": {"parent": 667419707, "title": "Armitron Men's Black Sunray Dial Silvertone Bracelet Watch", "category": "Watches"}, "B00RCUTIRM": {"parent": 731342946, "title": "Akribos XXIV Men's AK787YGBU Quartz Movement Watch with Blue Dial and Yellow Gold Stainless Steel Bracelet", "category": "Watches"}, "B00V30U79K": {"parent": 18936638, "title": "Topwell Mens Wood watches, Date Time 24hours Wooden watch with Round Multi-Eyed QUARTZ Wrist Watch for Gift", "category": "Watches"}, "B00STAXIHU": {"parent": 690763506, "title": "Fossil Women's ES3822 Georgia Stainless Steel Watch with Blue Leather Band", "category": "Watches"}, "B00DUW21F2": {"parent": 87555656, "title": "Stuhrling Original Men's 574.03 Analog Executive II Stainless Steel Automatic Skeleton Watch with Brown Leather Band", "category": "Watches"}, "B00MO38XL4": {"parent": 476271516, "title": "Armitron Sport Women's 25/6422BLK Easy to Read Dial Black Resin Strap Watch", "category": "Watches"}, "B00K8HMHCE": {"parent": 575505209, "title": "Swiss Legend Men's 10068-03 Commander II Analog Display Swiss Quartz Blue Watch", "category": "Watches"}, "B001DK6OKQ": {"parent": 79293794, "title": "Stuhrling Original Men's 219.331657 Symphony Eternity Monterey Swiss Quartz Date Watch", "category": "Watches"}, "B0094PS284": {"parent": 842528710, "title": "LuckyStore 14mm 5X Watch Band Stainless Steel Spring Bars Strap Link Pin Watchmaker New", "category": "Watches"}, "B00FDLB2S0": {"parent": 992050854, "title": "red line Men's RL-50042-YG-01 Stealth Chronograph Black Textured Dial Black Silicone Watch", "category": "Watches"}, "B00EVPMC88": {"parent": 516415826, "title": "Seiko Men's SNKL43 \"Seiko 5\" Stainless Steel Automatic Watch", "category": "Watches"}, "B00G2R7E3Q": {"parent": 131804424, "title": "Invicta Men's 14640 I-Force Analog Display Japanese Quartz Black Watch", "category": "Watches"}, "B004LURNO6": {"parent": 892860326, "title": "Nemesis #HST-K Unisex Black Wide Leather Cuff Wrist Watch Band", "category": "Watches"}, "B005OT1POW": {"parent": 202690497, "title": "Tommy Hilfiger  Women's 1781145 Sport Stainless Steel  Watch", "category": "Watches"}, "B007LPRLXG": {"parent": 973233011, "title": "GUESS U17531G1 - Bold and Sporty Watch Silver", "category": "Watches"}, "B00QK2HAFK": {"parent": 78116254, "title": "Armitron Men's 20/5048 Day/Date Function Dial Croco-Grain Leather Strap Watch", "category": "Watches"}, "B003X11UFM": {"parent": 790174403, "title": "Stuhrling Original Men's 238.321K43 Ascot Newberry Analog Swiss Quartz Brown Leather Watch", "category": "Watches"}, "B00A6OEWA4": {"parent": 985088364, "title": "AMPM24 Men's Hand-winding Mechanical Watch Black Leather Watchband Skeleton PMW069", "category": "Watches"}, "B006QAX906": {"parent": 957756572, "title": "Gotham Men's Silver-Tone Ultra Thin Railroad Open Face Quartz Pocket Watch # GWC15022S", "category": "Watches"}, "B00BS8U8PU": {"parent": 132047116, "title": "Casio Unisex MRW200H-2BV Neo-Display Black Watch with Resin Band", "category": "Watches"}, "B001F0PTNM": {"parent": 670846500, "title": "Hadley-Roma Men's MSM881RB-170 17-mm Brown Oil-Tan Leather Watch Strap", "category": "Watches"}, "B00Q7DETQU": {"parent": 763436398, "title": "Michael Kors Petite Silvertone Darci Watch", "category": "Watches"}, "B00LW3RP0W": {"parent": 198443125, "title": "Timex Expedition Rugged Metal Watch", "category": "Watches"}}

In [2]:
import pandas as pd

In [62]:
reviews = pd.read_excel("reviews-samples-new.xlsx",sheet_name=1)

In [44]:
reviews.head()

,marketplace,customer_id,product_title,product_category,verified_purchase,review_date
0,US,3653882,"Invicta Women's 15150 ""Angel"" 18k Yellow Gold ...",Watches,Y,2015-08-31
1,US,14661224,Kenneth Cole New York Women's KC4944 Automatic...,Watches,Y,2015-08-31
2,US,27324930,Ritche 22mm Black Stainless Steel Bracelet Wat...,Watches,Y,2015-08-31
3,US,7211452,Citizen Men's BM8180-03E Eco-Drive Stainless S...,Watches,Y,2015-08-31
4,US,12733322,Orient ER27009B Men's Symphony Automatic Stain...,Watches,Y,2015-08-31

In [46]:
reviews.shape

(99, 6)

In [10]:
reviews.tail()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
94,US,51897929,R2H287IH770TN7,B006QAX906,957756572,Gotham Men's Silver-Tone Ultra Thin Railroad O...,Watches,5,0,0,N,Y,Looks good.,Looks good. Not bulky. Keeps good time.,2015-08-31
95,US,48880662,R19SU6JVQQA05B,B00BS8U8PU,132047116,Casio Unisex MRW200H-2BV Neo-Display Black Wat...,Watches,5,0,0,N,Y,Five Stars,good,2015-08-31
96,US,39984561,R561PSHO7D095,B001F0PTNM,670846500,Hadley-Roma Men's MSM881RB-170 17-mm Brown Oil...,Watches,5,0,0,N,Y,Great leather watch band.,This is my 3rd Hadley Roma leather watch band....,2015-08-31
97,US,17141249,RUITIQHK33YXJ,B00Q7DETQU,763436398,Michael Kors Petite Silvertone Darci Watch,Watches,5,0,0,N,Y,petite watch - goes great with my engagement ring,"Gorgeous, petite watch - goes great with my en...",2015-08-31
98,US,29140914,R21BZGZC61EB1G,B00LW3RP0W,198443125,Timex Expedition Rugged Metal Watch,Watches,4,0,0,N,Y,Four Stars,heavier than expected,2015-08-31

In [22]:
reviews.query("verified_purchase=='Y'").loc[:,['marketplace','customer_id','verified_purchase']].head()

  marketplace  customer_id verified_purchase
0          US      3653882                 Y
1          US     14661224                 Y
2          US     27324930                 Y
3          US      7211452                 Y
4          US     12733322                 Y

In [52]:
review = pd.ExcelFile("reviews-samples-new.xlsx")

In [54]:
sheets = []

In [56]:
for sheet in review.sheet_names:
    sheets.append(review.parse(sheet))
reviews = pd.concat(sheets)

In [58]:
sheets

[   marketplace  customer_id       review_id  product_id  product_parent  \
 0           US      3653882  R3O9SGZBVQBV76  B00FALQ1ZC       937001370
 1           US     14661224   RKH8BNC3L5DLF  B00D3RGO20       484010722
 2           US     27324930  R2HLE8WKZSU3NL  B00DKYC7TK       361166390
 3           US      7211452  R31U3UH5AZ42LL  B000EQS1JW       958035625
 4           US     12733322  R2SV659OUJ945Y  B00A6GFD7S       765328221
 ..         ...          ...             ...         ...             ...
 94          US     51897929  R2H287IH770TN7  B006QAX906       957756572
 95          US     48880662  R19SU6JVQQA05B  B00BS8U8PU       132047116
 96          US     39984561   R561PSHO7D095  B001F0PTNM       670846500
 97          US     17141249   RUITIQHK33YXJ  B00Q7DETQU       763436398
 98          US     29140914  R21BZGZC61EB1G  B00LW3RP0W       198443125

                                         product_title product_category  \
 0   Invicta Women's 15150 "Angel" 18k Yellow Gold ...          Watches
 1   Kenneth Cole New York Women's KC4944 Automatic...          Watches
 2   Ritche 22mm Black Stainless Steel Bracelet Wat...          Watches
 3   Citizen Men's BM8180-03E Eco-Drive Stainless S...          Watches
 4   Orient ER27009B Men's Symphony Automatic Stain...          Watches
 ..                                                ...              ...
 94  Gotham Men's Silver-Tone Ultra Thin Railroad O...          Watches
 95  Casio Unisex MRW200H-2BV Neo-Display Black Wat...          Watches
 96  Hadley-Roma Men's MSM881RB-170 17-mm Brown Oil...          Watches
 97         Michael Kors Petite Silvertone Darci Watch          Watches
 98                Timex Expedition Rugged Metal Watch          Watches

     star_rating  helpful_votes  total_votes vine verified_purchase  \
 0             5              0            0    N                 Y
 1             5              0            0    N                 Y
 2             2              1            1    N                 Y
 3             5              0            0    N                 Y
 4             4              0            0    N                 Y
 ..          ...            ...          ...  ...               ...
 94            5              0            0    N                 Y
 95            5              0            0    N                 Y
 96            5              0            0    N                 Y
 97            5              0            0    N                 Y
 98            4              0            0    N                 Y

                                       review_headline  \
 0                                          Five Stars
 1          I love thiswatch it keeps time wonderfully
 2                                           Two Stars
 3                                          Five Stars
 4            Beautiful face, but cheap sounding links
 ..                                                ...
 94                                        Looks good.
 95                                         Five Stars
 96                          Great leather watch band.
 97  petite watch - goes great with my engagement ring
 98                                         Four Stars

                                           review_body review_date
 0   Absolutely love this watch! Get compliments al...  2015-08-31
 1        I love this watch it keeps time wonderfully.  2015-08-31
 2                                           Scratches  2015-08-31
 3   It works well on me. However, I found cheaper ...  2015-08-31
 4   Beautiful watch face.  The band looks nice all...  2015-08-31
 ..                                                ...         ...
 94            Looks good. Not bulky. Keeps good time.  2015-08-31
 95                                               good  2015-08-31
 96  This is my 3rd Hadley Roma leather watch band....  2015-08-31
 97  Gorgeous, petite watch - goes great with my en...  2015-08-31
 98                              heavier than expected  2015-08-31

 [99 rows x 15 columns],
    marketplace  customer_id  \
 0           US      3653882
 1           US     14661224
 2           US     27324930
 3           US      7211452
 4           US     12733322
 ..         ...          ...
 94          US     51897929
 95          US     48880662
 96          US     39984561
 97          US     17141249
 98          US     29140914

                                         product_title product_category  \
 0   Invicta Women's 15150 "Angel" 18k Yellow Gold ...          Watches
 1   Kenneth Cole New York Women's KC4944 Automatic...          Watches
 2   Ritche 22mm Black Stainless Steel Bracelet Wat...          Watches
 3   Citizen Men's BM8180-03E Eco-Drive Stainless S...          Watches
 4   Orient ER27009B Men's Symphony Automatic Stain...          Watches
 ..                                                ...              ...
 94  Gotham Men's Silver-Tone Ultra Thin Railroad O...          Watches
 95  Casio Unisex MRW200H-2BV Neo-Display Black Wat...          Watches
 96  Hadley-Roma Men's MSM881RB-170 17-mm Brown Oil...          Watches
 97         Michael Kors Petite Silvertone Darci Watch          Watches
 98                Timex Expedition Rugged Metal Watch          Watches

    verified_purchase review_date
 0                  Y  2015-08-31
 1                  Y  2015-08-31
 2                  Y  2015-08-31
 3                  Y  2015-08-31
 4                  Y  2015-08-31
 ..               ...         ...
 94                 Y  2015-08-31
 95                 Y  2015-08-31
 96                 Y  2015-08-31
 97                 Y  2015-08-31
 98                 Y  2015-08-31

 [99 rows x 6 columns]]

In [60]:
reviews.shape

(198, 15)

In [64]:
reviews.head()

,marketplace,customer_id,product_title,product_category,verified_purchase,review_date
0,US,3653882,"Invicta Women's 15150 ""Angel"" 18k Yellow Gold ...",Watches,Y,2015-08-31
1,US,14661224,Kenneth Cole New York Women's KC4944 Automatic...,Watches,Y,2015-08-31
2,US,27324930,Ritche 22mm Black Stainless Steel Bracelet Wat...,Watches,Y,2015-08-31
3,US,7211452,Citizen Men's BM8180-03E Eco-Drive Stainless S...,Watches,Y,2015-08-31
4,US,12733322,Orient ER27009B Men's Symphony Automatic Stain...,Watches,Y,2015-08-31

In [72]:
reviews_new = reviews.sort_values(['customer_id'],ascending=True)

In [74]:
reviews_new

,marketplace,customer_id,product_title,product_category,verified_purchase,review_date
82,US,106740,Swiss Legend Men's 10068-03 Commander II Analo...,Watches,Y,2015-08-31
89,US,107342,Tommy Hilfiger Women's 1781145 Sport Stainles...,Watches,Y,2015-08-31
32,US,112967,INFANTRY Mens 50mm Big Face Military Tactical ...,Watches,Y,2015-08-31
90,US,138028,GUESS U17531G1 - Bold and Sporty Watch Silver,Watches,N,2015-08-31
35,US,150916,Domire Fashion Accessories Trial Order New Qua...,Watches,Y,2015-08-31
...,...,...,...,...,...,...
12,US,51330346,2Tone Gold Silver Cable Band Ladies Bangle Cuf...,Watches,Y,2015-08-31
33,US,51346302,BUREI Dress Women's Minimalist Wrist Watches w...,Watches,N,2015-08-31
94,US,51897929,Gotham Men's Silver-Tone Ultra Thin Railroad O...,Watches,Y,2015-08-31
91,US,52229317,Armitron Men's 20/5048 Day/Date Function Dial ...,Watches,N,2015-08-31
38,US,52437550,Casio Men's Slim Solar Multi-Function Analog-D...,Watches,Y,2015-08-31

In [ ]:
reviews_new.plot(kind='barh')

In [77]:
reviews = pd.read_excel("reviews-samples-new.xlsx",sheet_name=1,header=None,skiprows=4)

In [79]:
reviews.shape

(96, 6)

In [81]:
reviews.head()

,0,1,2,3,4,5
0,US,7211452,Citizen Men's BM8180-03E Eco-Drive Stainless S...,Watches,Y,2015-08-31
1,US,12733322,Orient ER27009B Men's Symphony Automatic Stain...,Watches,Y,2015-08-31
2,US,6576411,Casio Men's GW-9400BJ-1JF G-Shock Master of G ...,Watches,Y,2015-08-31
3,US,11811565,Fossil Women's ES3851 Urban Traveler Multifunc...,Watches,Y,2015-08-31
4,US,49401598,INFANTRY Mens Night Vision Analog Quartz Wrist...,Watches,N,2015-08-31